/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_comment`]
#[derive(Clone, Debug)]
pub struct CreateCommentParams {
    pub draft_public_id: String,
    pub paper_draft_comment_create: models::PaperDraftCommentCreate,
}

/// struct for passing parameters to the method [`create_draft`]
#[derive(Clone, Debug)]
pub struct CreateDraftParams {
    pub paper_draft_create: models::PaperDraftCreate,
}

/// struct for passing parameters to the method [`create_or_update_collaborator`]
#[derive(Clone, Debug)]
pub struct CreateOrUpdateCollaboratorParams {
    pub draft_public_id: String,
    pub paper_draft_collaborator_create: models::PaperDraftCollaboratorCreate,
}

/// struct for passing parameters to the method [`delete_draft`]
#[derive(Clone, Debug)]
pub struct DeleteDraftParams {
    pub draft_public_id: String,
}

/// struct for passing parameters to the method [`download_draft`]
#[derive(Clone, Debug)]
pub struct DownloadDraftParams {
    pub draft_public_id: String,
    pub format: Option<String>,
}

/// struct for passing parameters to the method [`get_draft`]
#[derive(Clone, Debug)]
pub struct GetDraftParams {
    pub draft_public_id: String,
}

/// struct for passing parameters to the method [`patch_collaborator`]
#[derive(Clone, Debug)]
pub struct PatchCollaboratorParams {
    pub draft_public_id: String,
    pub user_public_id: String,
    pub paper_draft_collaborator_update: models::PaperDraftCollaboratorUpdate,
}

/// struct for passing parameters to the method [`patch_comment`]
#[derive(Clone, Debug)]
pub struct PatchCommentParams {
    pub draft_public_id: String,
    pub comment_public_id: String,
    pub paper_draft_comment_update: models::PaperDraftCommentUpdate,
}

/// struct for passing parameters to the method [`remove_collaborator`]
#[derive(Clone, Debug)]
pub struct RemoveCollaboratorParams {
    pub draft_public_id: String,
    pub user_public_id: String,
}

/// struct for passing parameters to the method [`update_draft`]
#[derive(Clone, Debug)]
pub struct UpdateDraftParams {
    pub draft_public_id: String,
    pub paper_draft_update: models::PaperDraftUpdate,
}

/// struct for typed errors of method [`create_comment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCommentError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateDraftError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_or_update_collaborator`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrUpdateCollaboratorError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDraftError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`download_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadDraftError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDraftError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_drafts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDraftsError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_collaborator`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchCollaboratorError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_comment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchCommentError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_collaborator`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveCollaboratorError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_draft`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateDraftError {
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

pub async fn create_comment(
    configuration: &configuration::Configuration,
    params: CreateCommentParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<CreateCommentError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/comments",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_comment_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCommentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn create_draft(
    configuration: &configuration::Configuration,
    params: CreateDraftParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<CreateDraftError>> {
    let uri_str = format!("{}/api/v1/drafts", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateDraftError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn create_or_update_collaborator(
    configuration: &configuration::Configuration,
    params: CreateOrUpdateCollaboratorParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<CreateOrUpdateCollaboratorError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/collaborators",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_collaborator_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateOrUpdateCollaboratorError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn delete_draft(
    configuration: &configuration::Configuration,
    params: DeleteDraftParams,
) -> Result<(), Error<DeleteDraftError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDraftError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn download_draft(
    configuration: &configuration::Configuration,
    params: DownloadDraftParams,
) -> Result<reqwest::Response, Error<DownloadDraftError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/download",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<DownloadDraftError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_draft(
    configuration: &configuration::Configuration,
    params: GetDraftParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<GetDraftError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDraftError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_drafts(
    configuration: &configuration::Configuration,
) -> Result<models::EnvelopeListPaperDraftSummary, Error<ListDraftsError>> {
    let uri_str = format!("{}/api/v1/drafts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopeListPaperDraftSummary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopeListPaperDraftSummary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListDraftsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn patch_collaborator(
    configuration: &configuration::Configuration,
    params: PatchCollaboratorParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<PatchCollaboratorError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/collaborators/{user_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id),
        user_public_id = crate::apis::urlencode(params.user_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_collaborator_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchCollaboratorError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn patch_comment(
    configuration: &configuration::Configuration,
    params: PatchCommentParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<PatchCommentError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/comments/{comment_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id),
        comment_public_id = crate::apis::urlencode(params.comment_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_comment_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchCommentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn remove_collaborator(
    configuration: &configuration::Configuration,
    params: RemoveCollaboratorParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<RemoveCollaboratorError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}/collaborators/{user_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id),
        user_public_id = crate::apis::urlencode(params.user_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveCollaboratorError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_draft(
    configuration: &configuration::Configuration,
    params: UpdateDraftParams,
) -> Result<models::EnvelopePaperDraftDetail, Error<UpdateDraftError>> {
    let uri_str = format!(
        "{}/api/v1/drafts/{draft_public_id}",
        configuration.base_path,
        draft_public_id = crate::apis::urlencode(params.draft_public_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-CSRF-Token", value);
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.paper_draft_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopePaperDraftDetail`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateDraftError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
