/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`ack_sync_cursor`]
#[derive(Clone, Debug)]
pub struct AckSyncCursorParams {
    pub sync_ack_request: models::SyncAckRequest,
}

/// struct for passing parameters to the method [`get_sync_snapshot`]
#[derive(Clone, Debug)]
pub struct GetSyncSnapshotParams {
    pub cursor: Option<String>,
    pub page_size: Option<i32>,
}

/// struct for passing parameters to the method [`pull_sync_changes`]
#[derive(Clone, Debug)]
pub struct PullSyncChangesParams {
    pub cursor: Option<String>,
    pub page_size: Option<i32>,
}

/// struct for passing parameters to the method [`push_sync_mutations`]
#[derive(Clone, Debug)]
pub struct PushSyncMutationsParams {
    pub sync_push_request: models::SyncPushRequest,
}

/// struct for typed errors of method [`ack_sync_cursor`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AckSyncCursorError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status410(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status426(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_sync_snapshot`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSyncSnapshotError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status410(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status426(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`pull_sync_changes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PullSyncChangesError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status410(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status426(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`push_sync_mutations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PushSyncMutationsError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status403(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    Status410(models::ErrorEnvelope),
    Status413(models::ErrorEnvelope),
    Status422(models::ErrorEnvelope),
    Status426(models::ErrorEnvelope),
    Status429(models::ErrorEnvelope),
    Status500(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

pub async fn ack_sync_cursor(
    configuration: &configuration::Configuration,
    params: AckSyncCursorParams,
) -> Result<models::EnvelopeSyncAckResponse, Error<AckSyncCursorError>> {
    let uri_str = format!("{}/api/v1/sync/ack", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.sync_ack_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopeSyncAckResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopeSyncAckResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AckSyncCursorError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_sync_snapshot(
    configuration: &configuration::Configuration,
    params: GetSyncSnapshotParams,
) -> Result<models::EnvelopeSyncSnapshotResponse, Error<GetSyncSnapshotError>> {
    let uri_str = format!("{}/api/v1/sync/snapshot", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopeSyncSnapshotResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopeSyncSnapshotResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSyncSnapshotError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn pull_sync_changes(
    configuration: &configuration::Configuration,
    params: PullSyncChangesParams,
) -> Result<models::EnvelopeSyncPullResponse, Error<PullSyncChangesError>> {
    let uri_str = format!("{}/api/v1/sync/pull", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopeSyncPullResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopeSyncPullResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PullSyncChangesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn push_sync_mutations(
    configuration: &configuration::Configuration,
    params: PushSyncMutationsParams,
) -> Result<models::EnvelopeSyncPushResponse, Error<PushSyncMutationsError>> {
    let uri_str = format!("{}/api/v1/sync/push", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.sync_push_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnvelopeSyncPushResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnvelopeSyncPushResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PushSyncMutationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
