/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentChunkReceipt {
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "missingChunks")]
    pub missing_chunks: Vec<i32>,
    #[serde(rename = "ordinal")]
    pub ordinal: i32,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "uploadId")]
    pub upload_id: String,
    #[serde(rename = "uploadedBytes")]
    pub uploaded_bytes: i32,
}

impl AttachmentChunkReceipt {
    pub fn new(
        duplicate: bool,
        missing_chunks: Vec<i32>,
        ordinal: i32,
        protocol_version: i32,
        upload_id: String,
        uploaded_bytes: i32,
    ) -> AttachmentChunkReceipt {
        AttachmentChunkReceipt {
            duplicate,
            missing_chunks,
            ordinal,
            protocol_version,
            upload_id,
            uploaded_bytes,
        }
    }
}
