/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentUploadInitiateRequest {
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
    #[serde(rename = "byteSize")]
    pub byte_size: i32,
    #[serde(rename = "chunkSize", skip_serializing_if = "Option::is_none")]
    pub chunk_size: Option<i32>,
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "idempotencyKey")]
    pub idempotency_key: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "targetEntityId")]
    pub target_entity_id: String,
}

impl AttachmentUploadInitiateRequest {
    pub fn new(
        attachment_id: String,
        byte_size: i32,
        content_hash: String,
        content_type: String,
        file_name: String,
        idempotency_key: String,
        protocol_version: i32,
        target_entity_id: String,
    ) -> AttachmentUploadInitiateRequest {
        AttachmentUploadInitiateRequest {
            attachment_id,
            byte_size,
            chunk_size: None,
            content_hash,
            content_type,
            file_name,
            idempotency_key,
            protocol_version,
            target_entity_id,
        }
    }
}
