/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentUploadStatus {
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
    #[serde(rename = "byteSize")]
    pub byte_size: i32,
    #[serde(rename = "chunkSize")]
    pub chunk_size: i32,
    #[serde(rename = "completed")]
    pub completed: bool,
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(rename = "deduplicated")]
    pub deduplicated: bool,
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "missingChunks")]
    pub missing_chunks: Vec<i32>,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "totalChunks")]
    pub total_chunks: i32,
    #[serde(rename = "uploadId")]
    pub upload_id: String,
    #[serde(rename = "uploadedBytes")]
    pub uploaded_bytes: i32,
}

impl AttachmentUploadStatus {
    pub fn new(
        attachment_id: String,
        byte_size: i32,
        chunk_size: i32,
        completed: bool,
        content_hash: String,
        deduplicated: bool,
        expires_at: chrono::DateTime<chrono::FixedOffset>,
        missing_chunks: Vec<i32>,
        protocol_version: i32,
        total_chunks: i32,
        upload_id: String,
        uploaded_bytes: i32,
    ) -> AttachmentUploadStatus {
        AttachmentUploadStatus {
            attachment_id,
            byte_size,
            chunk_size,
            completed,
            content_hash,
            deduplicated,
            expires_at,
            missing_chunks,
            protocol_version,
            total_chunks,
            upload_id,
            uploaded_bytes,
        }
    }
}
