/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSession {
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user")]
    pub user: Box<models::UserEntity>,
}

impl AuthSession {
    pub fn new(
        expires_at: chrono::DateTime<chrono::FixedOffset>,
        user: models::UserEntity,
    ) -> AuthSession {
        AuthSession {
            expires_at,
            user: Box::new(user),
        }
    }
}
