/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankUserRef {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl BankUserRef {
    pub fn new(display_name: String, public_id: String, username: String) -> BankUserRef {
        BankUserRef {
            display_name,
            public_id,
            username,
        }
    }
}
