/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BankListScope {
    #[serde(rename = "visible")]
    Visible,
    #[serde(rename = "owned")]
    Owned,
    #[serde(rename = "subscribed")]
    Subscribed,
    #[serde(rename = "public")]
    Public,
}

impl std::fmt::Display for BankListScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Visible => write!(f, "visible"),
            Self::Owned => write!(f, "owned"),
            Self::Subscribed => write!(f, "subscribed"),
            Self::Public => write!(f, "public"),
        }
    }
}

impl Default for BankListScope {
    fn default() -> BankListScope {
        Self::Visible
    }
}
