/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankPublicationEntity {
    #[serde(rename = "bankId")]
    pub bank_id: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "createdBy",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_by: Option<Option<Box<models::BankUserRef>>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "state")]
    pub state: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(
        rename = "withdrawnAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub withdrawn_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl BankPublicationEntity {
    pub fn new(
        bank_id: i32,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: i32,
        public_id: String,
        state: std::collections::HashMap<String, serde_json::Value>,
        version: i32,
    ) -> BankPublicationEntity {
        BankPublicationEntity {
            bank_id,
            created_at,
            created_by: None,
            id,
            public_id,
            state,
            version,
            withdrawn_at: None,
        }
    }
}
