/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankMemberUpdate {
    #[serde(rename = "role")]
    pub role: models::BankRole,
}

impl BankMemberUpdate {
    pub fn new(role: models::BankRole) -> BankMemberUpdate {
        BankMemberUpdate { role }
    }
}
