/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankMemberCreate {
    #[serde(rename = "role")]
    pub role: models::BankRole,
    #[serde(rename = "username")]
    pub username: String,
}

impl BankMemberCreate {
    pub fn new(role: models::BankRole, username: String) -> BankMemberCreate {
        BankMemberCreate { role, username }
    }
}
