/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BankVisibility {
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "team")]
    Team,
    #[serde(rename = "public")]
    Public,
}

impl std::fmt::Display for BankVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Private => write!(f, "private"),
            Self::Team => write!(f, "team"),
            Self::Public => write!(f, "public"),
        }
    }
}

impl Default for BankVisibility {
    fn default() -> BankVisibility {
        Self::Private
    }
}
