/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CorrectionCategory {
    #[serde(rename = "wrong_answer")]
    WrongAnswer,
    #[serde(rename = "unclear")]
    Unclear,
    #[serde(rename = "typo")]
    Typo,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for CorrectionCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WrongAnswer => write!(f, "wrong_answer"),
            Self::Unclear => write!(f, "unclear"),
            Self::Typo => write!(f, "typo"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for CorrectionCategory {
    fn default() -> CorrectionCategory {
        Self::WrongAnswer
    }
}
