/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceSessionEntity {
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "current")]
    pub current: bool,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "deviceName")]
    pub device_name: String,
    #[serde(rename = "lastSeenAt", deserialize_with = "Option::deserialize")]
    pub last_seen_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl DeviceSessionEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        current: bool,
        device_id: String,
        device_name: String,
        last_seen_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    ) -> DeviceSessionEntity {
        DeviceSessionEntity {
            created_at,
            current,
            device_id,
            device_name,
            last_seen_at,
        }
    }
}
