/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftDeletedEvent {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "payload")]
    pub payload: Box<models::DraftDeletedPayload>,
}

impl DraftDeletedEvent {
    pub fn new(event: Event, payload: models::DraftDeletedPayload) -> DraftDeletedEvent {
        DraftDeletedEvent {
            event,
            payload: Box::new(payload),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "draft.deleted")]
    DraftDeleted,
}

impl Default for Event {
    fn default() -> Event {
        Self::DraftDeleted
    }
}
