/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftChangedPayload {
    #[serde(rename = "actorId")]
    pub actor_id: i32,
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "reviewStatus")]
    pub review_status: String,
    #[serde(rename = "revision")]
    pub revision: i32,
}

impl DraftChangedPayload {
    pub fn new(
        actor_id: i32,
        draft_id: String,
        review_status: String,
        revision: i32,
    ) -> DraftChangedPayload {
        DraftChangedPayload {
            actor_id,
            draft_id,
            review_status,
            revision,
        }
    }
}
