/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftPresenceUpdateEvent {
    #[serde(rename = "activity")]
    pub activity: Activity,
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "event")]
    pub event: Event,
}

impl DraftPresenceUpdateEvent {
    pub fn new(activity: Activity, draft_id: String, event: Event) -> DraftPresenceUpdateEvent {
        DraftPresenceUpdateEvent {
            activity,
            draft_id,
            event,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Activity {
    #[serde(rename = "viewing")]
    Viewing,
    #[serde(rename = "editing")]
    Editing,
}

impl Default for Activity {
    fn default() -> Activity {
        Self::Viewing
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "draft.presence.update")]
    DraftPresenceUpdate,
}

impl Default for Event {
    fn default() -> Event {
        Self::DraftPresenceUpdate
    }
}
