/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftChangedEvent {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "payload")]
    pub payload: Box<models::DraftChangedPayload>,
}

impl DraftChangedEvent {
    pub fn new(event: Event, payload: models::DraftChangedPayload) -> DraftChangedEvent {
        DraftChangedEvent {
            event,
            payload: Box::new(payload),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "draft.updated")]
    DraftUpdated,
    #[serde(rename = "draft.review.updated")]
    DraftReviewUpdated,
    #[serde(rename = "draft.comment.created")]
    DraftCommentCreated,
    #[serde(rename = "draft.comment.updated")]
    DraftCommentUpdated,
}

impl Default for Event {
    fn default() -> Event {
        Self::DraftUpdated
    }
}
