/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftPresenceSnapshotPayload {
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "members")]
    pub members: Vec<models::DraftPresenceMember>,
}

impl DraftPresenceSnapshotPayload {
    pub fn new(
        draft_id: String,
        members: Vec<models::DraftPresenceMember>,
    ) -> DraftPresenceSnapshotPayload {
        DraftPresenceSnapshotPayload { draft_id, members }
    }
}
