/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftUnsubscribeEvent {
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "event")]
    pub event: Event,
}

impl DraftUnsubscribeEvent {
    pub fn new(draft_id: String, event: Event) -> DraftUnsubscribeEvent {
        DraftUnsubscribeEvent { draft_id, event }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "draft.unsubscribe")]
    DraftUnsubscribe,
}

impl Default for Event {
    fn default() -> Event {
        Self::DraftUnsubscribe
    }
}
