/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftPresenceMember {
    #[serde(rename = "activity")]
    pub activity: Activity,
    #[serde(rename = "lastSeenAt")]
    pub last_seen_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user")]
    pub user: Box<models::DraftUserRef>,
}

impl DraftPresenceMember {
    pub fn new(
        activity: Activity,
        last_seen_at: chrono::DateTime<chrono::FixedOffset>,
        user: models::DraftUserRef,
    ) -> DraftPresenceMember {
        DraftPresenceMember {
            activity,
            last_seen_at,
            user: Box::new(user),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Activity {
    #[serde(rename = "viewing")]
    Viewing,
    #[serde(rename = "editing")]
    Editing,
}

impl Default for Activity {
    fn default() -> Activity {
        Self::Viewing
    }
}
