/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DraftReviewStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "in_review")]
    InReview,
    #[serde(rename = "changes_requested")]
    ChangesRequested,
    #[serde(rename = "approved")]
    Approved,
}

impl std::fmt::Display for DraftReviewStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Draft => write!(f, "draft"),
            Self::InReview => write!(f, "in_review"),
            Self::ChangesRequested => write!(f, "changes_requested"),
            Self::Approved => write!(f, "approved"),
        }
    }
}

impl Default for DraftReviewStatus {
    fn default() -> DraftReviewStatus {
        Self::Draft
    }
}
