/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvelopeListUserEntity {
    #[serde(rename = "data")]
    pub data: Vec<models::UserEntity>,
    #[serde(rename = "meta")]
    pub meta: Box<models::MetaInfo>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<Success>,
}

impl EnvelopeListUserEntity {
    pub fn new(data: Vec<models::UserEntity>, meta: models::MetaInfo) -> EnvelopeListUserEntity {
        EnvelopeListUserEntity {
            data,
            meta: Box::new(meta),
            success: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Success {
    #[serde(rename = "true")]
    True,
}

impl Default for Success {
    fn default() -> Success {
        Self::True
    }
}
