/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorEvent {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "payload")]
    pub payload: Box<models::ErrorPayload>,
}

impl ErrorEvent {
    pub fn new(event: Event, payload: models::ErrorPayload) -> ErrorEvent {
        ErrorEvent {
            event,
            payload: Box::new(payload),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "error")]
    Error,
}

impl Default for Event {
    fn default() -> Event {
        Self::Error
    }
}
