/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorEnvelope {
    #[serde(rename = "error")]
    pub error: Box<models::ErrorDetail>,
    #[serde(rename = "meta")]
    pub meta: Box<models::MetaInfo>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<Success>,
}

impl ErrorEnvelope {
    pub fn new(error: models::ErrorDetail, meta: models::MetaInfo) -> ErrorEnvelope {
        ErrorEnvelope {
            error: Box::new(error),
            meta: Box::new(meta),
            success: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Success {
    #[serde(rename = "false")]
    False,
}

impl Default for Success {
    fn default() -> Success {
        Self::False
    }
}
