/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EssayBlankSpace {
    #[serde(rename = "lineHeight")]
    pub line_height: i32,
    #[serde(rename = "lines")]
    pub lines: i32,
}

impl EssayBlankSpace {
    pub fn new(line_height: i32, lines: i32) -> EssayBlankSpace {
        EssayBlankSpace { line_height, lines }
    }
}
