/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportPreviewRequest {
    #[serde(rename = "includeAnswer", skip_serializing_if = "Option::is_none")]
    pub include_answer: Option<bool>,
    #[serde(rename = "layoutDensity", skip_serializing_if = "Option::is_none")]
    pub layout_density: Option<models::LayoutDensity>,
    #[serde(rename = "questionOrder", skip_serializing_if = "Option::is_none")]
    pub question_order: Option<models::QuestionOrder>,
}

impl ExportPreviewRequest {
    pub fn new() -> ExportPreviewRequest {
        ExportPreviewRequest {
            include_answer: None,
            layout_density: None,
            question_order: None,
        }
    }
}
