/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerationTypeTarget {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "questionType")]
    pub question_type: models::QuestionType,
}

impl GenerationTypeTarget {
    pub fn new(count: i32, question_type: models::QuestionType) -> GenerationTypeTarget {
        GenerationTypeTarget {
            count,
            question_type,
        }
    }
}
