/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageUploadPayload {
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

impl ImageUploadPayload {
    pub fn new(data: String, filename: String) -> ImageUploadPayload {
        ImageUploadPayload {
            data,
            filename,
            mime_type: None,
        }
    }
}
