/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedResponseQuestionEntity {
    #[serde(rename = "items")]
    pub items: Vec<models::QuestionEntity>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::PaginationInfo>,
}

impl PaginatedResponseQuestionEntity {
    pub fn new(
        items: Vec<models::QuestionEntity>,
        pagination: models::PaginationInfo,
    ) -> PaginatedResponseQuestionEntity {
        PaginatedResponseQuestionEntity {
            items,
            pagination: Box::new(pagination),
        }
    }
}
