/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftCommentEntity {
    #[serde(
        rename = "author",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub author: Option<Option<Box<models::DraftUserRef>>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(
        rename = "questionPublicId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub question_public_id: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::DraftCommentStatus,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PaperDraftCommentEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: i32,
        message: String,
        public_id: String,
        status: models::DraftCommentStatus,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaperDraftCommentEntity {
        PaperDraftCommentEntity {
            author: None,
            created_at,
            id,
            message,
            public_id,
            question_public_id: None,
            status,
            updated_at,
        }
    }
}
