/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftCreate {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "reviewStatus", skip_serializing_if = "Option::is_none")]
    pub review_status: Option<models::DraftReviewStatus>,
    #[serde(rename = "state")]
    pub state: std::collections::HashMap<String, serde_json::Value>,
}

impl PaperDraftCreate {
    pub fn new(
        name: String,
        state: std::collections::HashMap<String, serde_json::Value>,
    ) -> PaperDraftCreate {
        PaperDraftCreate {
            name,
            review_status: None,
            state,
        }
    }
}
