/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperQuestionsChangedPayload {
    #[serde(rename = "actorId")]
    pub actor_id: i32,
    #[serde(rename = "paper")]
    pub paper: Box<models::PaperEntity>,
    #[serde(rename = "paperId")]
    pub paper_id: String,
}

impl PaperQuestionsChangedPayload {
    pub fn new(
        actor_id: i32,
        paper: models::PaperEntity,
        paper_id: String,
    ) -> PaperQuestionsChangedPayload {
        PaperQuestionsChangedPayload {
            actor_id,
            paper: Box::new(paper),
            paper_id,
        }
    }
}
