/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftCollaboratorEntity {
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "role")]
    pub role: models::DraftCollaboratorRole,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user")]
    pub user: Box<models::DraftUserRef>,
}

impl PaperDraftCollaboratorEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        role: models::DraftCollaboratorRole,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        user: models::DraftUserRef,
    ) -> PaperDraftCollaboratorEntity {
        PaperDraftCollaboratorEntity {
            created_at,
            role,
            updated_at,
            user: Box::new(user),
        }
    }
}
