/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftSummary {
    #[serde(rename = "accessRole")]
    pub access_role: models::DraftAccessRole,
    #[serde(rename = "collaboratorCount")]
    pub collaborator_count: i32,
    #[serde(rename = "commentCount")]
    pub comment_count: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "openCommentCount")]
    pub open_comment_count: i32,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<models::DraftUserRef>>>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "reviewStatus")]
    pub review_status: models::DraftReviewStatus,
    #[serde(rename = "revision")]
    pub revision: i32,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "updatedBy",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_by: Option<Option<Box<models::DraftUserRef>>>,
}

impl PaperDraftSummary {
    pub fn new(
        access_role: models::DraftAccessRole,
        collaborator_count: i32,
        comment_count: i32,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: i32,
        name: String,
        open_comment_count: i32,
        public_id: String,
        review_status: models::DraftReviewStatus,
        revision: i32,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaperDraftSummary {
        PaperDraftSummary {
            access_role,
            collaborator_count,
            comment_count,
            created_at,
            id,
            name,
            open_comment_count,
            owner: None,
            public_id,
            review_status,
            revision,
            updated_at,
            updated_by: None,
        }
    }
}
