/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftCommentCreate {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(
        rename = "questionPublicId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub question_public_id: Option<Option<String>>,
}

impl PaperDraftCommentCreate {
    pub fn new(message: String) -> PaperDraftCommentCreate {
        PaperDraftCommentCreate {
            message,
            question_public_id: None,
        }
    }
}
