/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftQuestion {
    #[serde(rename = "answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<Box<models::Answer>>,
    #[serde(rename = "difficulty", skip_serializing_if = "Option::is_none")]
    pub difficulty: Option<models::Difficulty>,
    #[serde(
        rename = "essayBlankSpace",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub essay_blank_space: Option<Option<Box<models::EssayBlankSpace>>>,
    #[serde(rename = "hasLatex", skip_serializing_if = "Option::is_none")]
    pub has_latex: Option<bool>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::QuestionImage>>,
    #[serde(
        rename = "marks",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub marks: Option<Option<i32>>,
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<Vec<String>>>,
    #[serde(rename = "orderNo")]
    pub order_no: i32,
    #[serde(rename = "questionPublicId")]
    pub question_public_id: String,
    #[serde(rename = "scoreWeight", skip_serializing_if = "Option::is_none")]
    pub score_weight: Option<f64>,
    #[serde(
        rename = "source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<Option<String>>,
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type")]
    pub r#type: models::QuestionType,
}

impl PaperDraftQuestion {
    pub fn new(
        order_no: i32,
        question_public_id: String,
        text: String,
        r#type: models::QuestionType,
    ) -> PaperDraftQuestion {
        PaperDraftQuestion {
            answer: None,
            difficulty: None,
            essay_blank_space: None,
            has_latex: None,
            images: None,
            marks: None,
            options: None,
            order_no,
            question_public_id,
            score_weight: None,
            source: None,
            subjects: None,
            tags: None,
            text,
            r#type,
        }
    }
}
