/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperExpandedEntity {
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "duration")]
    pub duration: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(
        rename = "ownerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<i32>>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "questions")]
    pub questions: Vec<models::PaperQuestionEntity>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PaperStatus>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "totalMarks")]
    pub total_marks: i32,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PaperExpandedEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        duration: i32,
        id: i32,
        public_id: String,
        questions: Vec<models::PaperQuestionEntity>,
        subject: String,
        title: String,
        total_marks: i32,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaperExpandedEntity {
        PaperExpandedEntity {
            created_at,
            duration,
            id,
            owner_id: None,
            public_id,
            questions,
            status: None,
            subject,
            title,
            total_marks,
            updated_at,
        }
    }
}
