/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftDownloadRequest {
    #[serde(rename = "duration")]
    pub duration: i32,
    #[serde(rename = "includeAnswer", skip_serializing_if = "Option::is_none")]
    pub include_answer: Option<bool>,
    #[serde(rename = "layoutDensity", skip_serializing_if = "Option::is_none")]
    pub layout_density: Option<models::LayoutDensity>,
    #[serde(rename = "questionOrder", skip_serializing_if = "Option::is_none")]
    pub question_order: Option<models::QuestionOrder>,
    #[serde(rename = "questions")]
    pub questions: Vec<models::PaperDraftQuestion>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "totalMarks")]
    pub total_marks: i32,
}

impl PaperDraftDownloadRequest {
    pub fn new(
        duration: i32,
        questions: Vec<models::PaperDraftQuestion>,
        subject: String,
        title: String,
        total_marks: i32,
    ) -> PaperDraftDownloadRequest {
        PaperDraftDownloadRequest {
            duration,
            include_answer: None,
            layout_density: None,
            question_order: None,
            questions,
            subject,
            title,
            total_marks,
        }
    }
}
