/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperCreate {
    #[serde(rename = "duration")]
    pub duration: i32,
    #[serde(
        rename = "ownerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<i32>>,
    #[serde(rename = "questions", skip_serializing_if = "Option::is_none")]
    pub questions: Option<Vec<models::QuestionRef>>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "totalMarks")]
    pub total_marks: i32,
}

impl PaperCreate {
    pub fn new(duration: i32, subject: String, title: String, total_marks: i32) -> PaperCreate {
        PaperCreate {
            duration,
            owner_id: None,
            questions: None,
            subject,
            title,
            total_marks,
        }
    }
}
