/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperQuestionEntity {
    #[serde(rename = "answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<Box<models::Answer>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "difficulty")]
    pub difficulty: models::Difficulty,
    #[serde(
        rename = "essayBlankSpace",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub essay_blank_space: Option<Option<Box<models::EssayBlankSpace>>>,
    #[serde(
        rename = "hasLatex",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_latex: Option<Option<bool>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::QuestionImage>>,
    #[serde(
        rename = "marks",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub marks: Option<Option<i32>>,
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<Vec<String>>>,
    #[serde(rename = "orderNo")]
    pub order_no: i32,
    #[serde(
        rename = "ownerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<i32>>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "questionPublicId")]
    pub question_public_id: String,
    #[serde(rename = "scoreWeight", skip_serializing_if = "Option::is_none")]
    pub score_weight: Option<f64>,
    #[serde(
        rename = "source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<Option<String>>,
    #[serde(rename = "subjects")]
    pub subjects: Vec<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type")]
    pub r#type: models::QuestionType,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PaperQuestionEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        difficulty: models::Difficulty,
        id: i32,
        order_no: i32,
        public_id: String,
        question_public_id: String,
        subjects: Vec<String>,
        text: String,
        r#type: models::QuestionType,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaperQuestionEntity {
        PaperQuestionEntity {
            answer: None,
            created_at,
            difficulty,
            essay_blank_space: None,
            has_latex: None,
            id,
            images: None,
            marks: None,
            options: None,
            order_no,
            owner_id: None,
            public_id,
            question_public_id,
            score_weight: None,
            source: None,
            subjects,
            tags: None,
            text,
            r#type,
            updated_at,
        }
    }
}
