/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperChangedPayload {
    #[serde(rename = "actorId")]
    pub actor_id: i32,
    #[serde(rename = "paper")]
    pub paper: Box<models::PaperEntity>,
}

impl PaperChangedPayload {
    pub fn new(actor_id: i32, paper: models::PaperEntity) -> PaperChangedPayload {
        PaperChangedPayload {
            actor_id,
            paper: Box::new(paper),
        }
    }
}
