/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaperDraftCollaboratorCreate {
    #[serde(rename = "role")]
    pub role: models::DraftCollaboratorRole,
    #[serde(rename = "username")]
    pub username: String,
}

impl PaperDraftCollaboratorCreate {
    pub fn new(
        role: models::DraftCollaboratorRole,
        username: String,
    ) -> PaperDraftCollaboratorCreate {
        PaperDraftCollaboratorCreate { role, username }
    }
}
