/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PongPayload {
    #[serde(rename = "serverTime")]
    pub server_time: chrono::DateTime<chrono::FixedOffset>,
}

impl PongPayload {
    pub fn new(server_time: chrono::DateTime<chrono::FixedOffset>) -> PongPayload {
        PongPayload { server_time }
    }
}
