/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicBankSummary {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "itemCount", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<models::BankUserRef>>>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "publishedAt")]
    pub published_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "subscriberCount", skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    #[serde(rename = "version")]
    pub version: i32,
}

impl PublicBankSummary {
    pub fn new(
        description: String,
        name: String,
        public_id: String,
        published_at: chrono::DateTime<chrono::FixedOffset>,
        version: i32,
    ) -> PublicBankSummary {
        PublicBankSummary {
            description,
            item_count: None,
            name,
            owner: None,
            public_id,
            published_at,
            subscriber_count: None,
            version,
        }
    }
}
