/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionDeletedPayload {
    #[serde(rename = "actorId")]
    pub actor_id: i32,
    #[serde(rename = "questionId")]
    pub question_id: String,
}

impl QuestionDeletedPayload {
    pub fn new(actor_id: i32, question_id: String) -> QuestionDeletedPayload {
        QuestionDeletedPayload {
            actor_id,
            question_id,
        }
    }
}
