/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionOrderItem {
    #[serde(rename = "orderNo")]
    pub order_no: i32,
    #[serde(rename = "questionPublicId")]
    pub question_public_id: String,
}

impl QuestionOrderItem {
    pub fn new(order_no: i32, question_public_id: String) -> QuestionOrderItem {
        QuestionOrderItem {
            order_no,
            question_public_id,
        }
    }
}
