/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionChangedPayload {
    #[serde(rename = "actorId")]
    pub actor_id: i32,
    #[serde(rename = "question")]
    pub question: Box<models::QuestionEntity>,
}

impl QuestionChangedPayload {
    pub fn new(actor_id: i32, question: models::QuestionEntity) -> QuestionChangedPayload {
        QuestionChangedPayload {
            actor_id,
            question: Box::new(question),
        }
    }
}
