/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionRevisionEntity {
    #[serde(rename = "changeSummary")]
    pub change_summary: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "patch")]
    pub patch: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "questionId")]
    pub question_id: i32,
    #[serde(rename = "userId", deserialize_with = "Option::deserialize")]
    pub user_id: Option<i32>,
}

impl QuestionRevisionEntity {
    pub fn new(
        change_summary: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: i32,
        patch: std::collections::HashMap<String, serde_json::Value>,
        question_id: i32,
        user_id: Option<i32>,
    ) -> QuestionRevisionEntity {
        QuestionRevisionEntity {
            change_summary,
            created_at,
            id,
            patch,
            question_id,
            user_id,
        }
    }
}
