/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionRef {
    #[serde(
        rename = "marks",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub marks: Option<Option<i32>>,
    #[serde(rename = "orderNo")]
    pub order_no: i32,
    #[serde(rename = "questionPublicId")]
    pub question_public_id: String,
}

impl QuestionRef {
    pub fn new(order_no: i32, question_public_id: String) -> QuestionRef {
        QuestionRef {
            marks: None,
            order_no,
            question_public_id,
        }
    }
}
