/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuestionOrder {
    #[serde(rename = "paper")]
    Paper,
    #[serde(rename = "categorized")]
    Categorized,
}

impl std::fmt::Display for QuestionOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Paper => write!(f, "paper"),
            Self::Categorized => write!(f, "categorized"),
        }
    }
}

impl Default for QuestionOrder {
    fn default() -> QuestionOrder {
        Self::Paper
    }
}
