/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuestionType {
    #[serde(rename = "single_choice")]
    SingleChoice,
    #[serde(rename = "multiple_choice")]
    MultipleChoice,
    #[serde(rename = "true_false")]
    TrueFalse,
    #[serde(rename = "blank")]
    Blank,
    #[serde(rename = "short_answer")]
    ShortAnswer,
    #[serde(rename = "essay")]
    Essay,
}

impl std::fmt::Display for QuestionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SingleChoice => write!(f, "single_choice"),
            Self::MultipleChoice => write!(f, "multiple_choice"),
            Self::TrueFalse => write!(f, "true_false"),
            Self::Blank => write!(f, "blank"),
            Self::ShortAnswer => write!(f, "short_answer"),
            Self::Essay => write!(f, "essay"),
        }
    }
}

impl Default for QuestionType {
    fn default() -> QuestionType {
        Self::SingleChoice
    }
}
