/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionCreate {
    #[serde(rename = "answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<Box<models::Answer>>,
    #[serde(rename = "difficulty")]
    pub difficulty: models::Difficulty,
    #[serde(
        rename = "essayBlankSpace",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub essay_blank_space: Option<Option<Box<models::EssayBlankSpace>>>,
    #[serde(
        rename = "hasLatex",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_latex: Option<Option<bool>>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::QuestionImage>>,
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<Vec<String>>>,
    #[serde(
        rename = "ownerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<i32>>,
    #[serde(rename = "scoreWeight", skip_serializing_if = "Option::is_none")]
    pub score_weight: Option<f64>,
    #[serde(
        rename = "source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<Option<String>>,
    #[serde(rename = "subjects")]
    pub subjects: Vec<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type")]
    pub r#type: models::QuestionType,
}

impl QuestionCreate {
    pub fn new(
        difficulty: models::Difficulty,
        subjects: Vec<String>,
        text: String,
        r#type: models::QuestionType,
    ) -> QuestionCreate {
        QuestionCreate {
            answer: None,
            difficulty,
            essay_blank_space: None,
            has_latex: None,
            images: None,
            options: None,
            owner_id: None,
            score_weight: None,
            source: None,
            subjects,
            tags: None,
            text,
            r#type,
        }
    }
}
