/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionCorrectionEntity {
    #[serde(rename = "category")]
    pub category: models::CorrectionCategory,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "questionId")]
    pub question_id: i32,
    #[serde(rename = "status")]
    pub status: models::CorrectionStatus,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "userId", deserialize_with = "Option::deserialize")]
    pub user_id: Option<i32>,
}

impl QuestionCorrectionEntity {
    pub fn new(
        category: models::CorrectionCategory,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: i32,
        message: String,
        question_id: i32,
        status: models::CorrectionStatus,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        user_id: Option<i32>,
    ) -> QuestionCorrectionEntity {
        QuestionCorrectionEntity {
            category,
            created_at,
            id,
            message,
            question_id,
            status,
            updated_at,
            user_id,
        }
    }
}
