/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionBankEntity {
    #[serde(rename = "accessRole")]
    pub access_role: models::BankAccessRole,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "hasUpdate", skip_serializing_if = "Option::is_none")]
    pub has_update: Option<bool>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "isSubscribed", skip_serializing_if = "Option::is_none")]
    pub is_subscribed: Option<bool>,
    #[serde(rename = "itemCount", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    #[serde(rename = "memberCount", skip_serializing_if = "Option::is_none")]
    pub member_count: Option<i32>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::BankMemberEntity>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "owner",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner: Option<Option<Box<models::BankUserRef>>>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(
        rename = "subscribedVersion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscribed_version: Option<Option<i32>>,
    #[serde(rename = "subscriberCount", skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub version: Option<Option<i32>>,
    #[serde(rename = "visibility")]
    pub visibility: models::BankVisibility,
}

impl QuestionBankEntity {
    pub fn new(
        access_role: models::BankAccessRole,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        description: String,
        id: i32,
        name: String,
        public_id: String,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        visibility: models::BankVisibility,
    ) -> QuestionBankEntity {
        QuestionBankEntity {
            access_role,
            created_at,
            description,
            has_update: None,
            id,
            is_subscribed: None,
            item_count: None,
            member_count: None,
            members: None,
            name,
            owner: None,
            public_id,
            subscribed_version: None,
            subscriber_count: None,
            updated_at,
            version: None,
            visibility,
        }
    }
}
