/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionChangedEvent {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "eventId", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<uuid::Uuid>,
    #[serde(rename = "occurredAt", skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "payload")]
    pub payload: Box<models::QuestionChangedPayload>,
}

impl QuestionChangedEvent {
    pub fn new(event: Event, payload: models::QuestionChangedPayload) -> QuestionChangedEvent {
        QuestionChangedEvent {
            event,
            event_id: None,
            occurred_at: None,
            payload: Box::new(payload),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "question.created")]
    QuestionCreated,
    #[serde(rename = "question.updated")]
    QuestionUpdated,
}

impl Default for Event {
    fn default() -> Event {
        Self::QuestionCreated
    }
}
