/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event")]
pub enum RealtimeServerMessage {
    #[serde(rename = "auth.connected")]
    AuthConnected(Box<models::AuthConnectedEvent>),
    #[serde(rename = "error")]
    Error(Box<models::ErrorEvent>),
    #[serde(rename = "pong")]
    Pong(Box<models::PongEvent>),
    #[serde(rename = "question.created")]
    QuestionCreated(Box<models::QuestionChangedEvent>),
    #[serde(rename = "question.deleted")]
    QuestionDeleted(Box<models::QuestionDeletedEvent>),
    #[serde(rename = "paper.created")]
    PaperCreated(Box<models::PaperChangedEvent>),
    #[serde(rename = "paper.questions.added")]
    PaperQuestionsAdded(Box<models::PaperQuestionsChangedEvent>),
    #[serde(rename = "paper.question.removed")]
    PaperQuestionRemoved(Box<models::PaperQuestionRemovedEvent>),
    #[serde(rename = "draft.comment.created")]
    DraftCommentCreated(Box<models::DraftChangedEvent>),
    #[serde(rename = "draft.deleted")]
    DraftDeleted(Box<models::DraftDeletedEvent>),
    #[serde(rename = "draft.presence.snapshot")]
    DraftPresenceSnapshot(Box<models::DraftPresenceSnapshotEvent>),
    #[serde(rename = "draft.collaborators.updated")]
    DraftCollaboratorsUpdated(Box<models::DraftCollaboratorsUpdatedEvent>),
}

impl Default for RealtimeServerMessage {
    fn default() -> Self {
        Self::AuthConnected(Default::default())
    }
}
