/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event")]
pub enum RealtimeClientMessage {
    #[serde(rename = "ping")]
    Ping(Box<models::RealtimePing>),
    #[serde(rename = "draft.subscribe")]
    DraftSubscribe(Box<models::DraftSubscribeEvent>),
    #[serde(rename = "draft.unsubscribe")]
    DraftUnsubscribe(Box<models::DraftUnsubscribeEvent>),
    #[serde(rename = "draft.presence.update")]
    DraftPresenceUpdate(Box<models::DraftPresenceUpdateEvent>),
}

impl Default for RealtimeClientMessage {
    fn default() -> Self {
        Self::Ping(Default::default())
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Activity {
    #[serde(rename = "viewing")]
    Viewing,
    #[serde(rename = "editing")]
    Editing,
}

impl Default for Activity {
    fn default() -> Activity {
        Self::Viewing
    }
}
