/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncMutation {
    #[serde(
        rename = "baseContentHash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_content_hash: Option<Option<String>>,
    #[serde(
        rename = "baseVersion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_version: Option<Option<i32>>,
    #[serde(rename = "dependsOn", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    #[serde(rename = "entityType")]
    pub entity_type: models::SyncEntityType,
    #[serde(rename = "kind")]
    pub kind: models::SyncMutationKind,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(
        rename = "payload",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payload: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl SyncMutation {
    pub fn new(
        entity_id: String,
        entity_type: models::SyncEntityType,
        kind: models::SyncMutationKind,
        operation_id: String,
    ) -> SyncMutation {
        SyncMutation {
            base_content_hash: None,
            base_version: None,
            depends_on: None,
            entity_id,
            entity_type,
            kind,
            operation_id,
            payload: None,
        }
    }
}
