/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncChange {
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    #[serde(rename = "entityType")]
    pub entity_type: models::SyncEntityType,
    #[serde(rename = "kind")]
    pub kind: models::SyncMutationKind,
    #[serde(rename = "sequence")]
    pub sequence: String,
    #[serde(
        rename = "snapshot",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub snapshot: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "version")]
    pub version: i32,
}

impl SyncChange {
    pub fn new(
        content_hash: String,
        entity_id: String,
        entity_type: models::SyncEntityType,
        kind: models::SyncMutationKind,
        sequence: String,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        version: i32,
    ) -> SyncChange {
        SyncChange {
            content_hash,
            entity_id,
            entity_type,
            kind,
            sequence,
            snapshot: None,
            updated_at,
            version,
        }
    }
}
