/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncSnapshotResponse {
    #[serde(rename = "entries")]
    pub entries: Vec<models::SyncChange>,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    #[serde(rename = "nextCursor")]
    pub next_cursor: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "resumeCursor")]
    pub resume_cursor: String,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: String,
}

impl SyncSnapshotResponse {
    pub fn new(
        entries: Vec<models::SyncChange>,
        has_more: bool,
        next_cursor: String,
        protocol_version: i32,
        resume_cursor: String,
        snapshot_id: String,
    ) -> SyncSnapshotResponse {
        SyncSnapshotResponse {
            entries,
            has_more,
            next_cursor,
            protocol_version,
            resume_cursor,
            snapshot_id,
        }
    }
}
