/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncErrorCode {
    #[serde(rename = "SYNC_PROTOCOL_UNSUPPORTED")]
    SyncProtocolUnsupported,
    #[serde(rename = "SYNC_BATCH_INVALID")]
    SyncBatchInvalid,
    #[serde(rename = "SYNC_BATCH_TOO_LARGE")]
    SyncBatchTooLarge,
    #[serde(rename = "SYNC_IDEMPOTENCY_MISMATCH")]
    SyncIdempotencyMismatch,
    #[serde(rename = "SYNC_DEPENDENCY_FAILED")]
    SyncDependencyFailed,
    #[serde(rename = "SYNC_CONFLICT")]
    SyncConflict,
    #[serde(rename = "SYNC_CURSOR_INVALID")]
    SyncCursorInvalid,
    #[serde(rename = "SYNC_CURSOR_EXPIRED")]
    SyncCursorExpired,
    #[serde(rename = "SYNC_SNAPSHOT_EXPIRED")]
    SyncSnapshotExpired,
    #[serde(rename = "SYNC_ENTITY_FORBIDDEN")]
    SyncEntityForbidden,
    #[serde(rename = "SYNC_ENTITY_NOT_FOUND")]
    SyncEntityNotFound,
    #[serde(rename = "SYNC_ENTITY_SCHEMA_UNSUPPORTED")]
    SyncEntitySchemaUnsupported,
    #[serde(rename = "SYNC_UPLOAD_EXPIRED")]
    SyncUploadExpired,
    #[serde(rename = "SYNC_UPLOAD_CHUNK_MISMATCH")]
    SyncUploadChunkMismatch,
    #[serde(rename = "SYNC_UPLOAD_INCOMPLETE")]
    SyncUploadIncomplete,
    #[serde(rename = "SYNC_ATTACHMENT_HASH_MISMATCH")]
    SyncAttachmentHashMismatch,
}

impl std::fmt::Display for SyncErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SyncProtocolUnsupported => write!(f, "SYNC_PROTOCOL_UNSUPPORTED"),
            Self::SyncBatchInvalid => write!(f, "SYNC_BATCH_INVALID"),
            Self::SyncBatchTooLarge => write!(f, "SYNC_BATCH_TOO_LARGE"),
            Self::SyncIdempotencyMismatch => write!(f, "SYNC_IDEMPOTENCY_MISMATCH"),
            Self::SyncDependencyFailed => write!(f, "SYNC_DEPENDENCY_FAILED"),
            Self::SyncConflict => write!(f, "SYNC_CONFLICT"),
            Self::SyncCursorInvalid => write!(f, "SYNC_CURSOR_INVALID"),
            Self::SyncCursorExpired => write!(f, "SYNC_CURSOR_EXPIRED"),
            Self::SyncSnapshotExpired => write!(f, "SYNC_SNAPSHOT_EXPIRED"),
            Self::SyncEntityForbidden => write!(f, "SYNC_ENTITY_FORBIDDEN"),
            Self::SyncEntityNotFound => write!(f, "SYNC_ENTITY_NOT_FOUND"),
            Self::SyncEntitySchemaUnsupported => write!(f, "SYNC_ENTITY_SCHEMA_UNSUPPORTED"),
            Self::SyncUploadExpired => write!(f, "SYNC_UPLOAD_EXPIRED"),
            Self::SyncUploadChunkMismatch => write!(f, "SYNC_UPLOAD_CHUNK_MISMATCH"),
            Self::SyncUploadIncomplete => write!(f, "SYNC_UPLOAD_INCOMPLETE"),
            Self::SyncAttachmentHashMismatch => write!(f, "SYNC_ATTACHMENT_HASH_MISMATCH"),
        }
    }
}

impl Default for SyncErrorCode {
    fn default() -> SyncErrorCode {
        Self::SyncProtocolUnsupported
    }
}
