/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncEntityType {
    #[serde(rename = "question")]
    Question,
    #[serde(rename = "paper")]
    Paper,
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "attachment")]
    Attachment,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "favorite")]
    Favorite,
    #[serde(rename = "setting")]
    Setting,
}

impl std::fmt::Display for SyncEntityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Question => write!(f, "question"),
            Self::Paper => write!(f, "paper"),
            Self::Draft => write!(f, "draft"),
            Self::Attachment => write!(f, "attachment"),
            Self::Comment => write!(f, "comment"),
            Self::Favorite => write!(f, "favorite"),
            Self::Setting => write!(f, "setting"),
        }
    }
}

impl Default for SyncEntityType {
    fn default() -> SyncEntityType {
        Self::Question
    }
}
