/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncEntityVersionRecord {
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    #[serde(rename = "entityType")]
    pub entity_type: models::SyncEntityType,
    #[serde(rename = "mutationKind")]
    pub mutation_kind: models::SyncMutationKind,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(rename = "payload", deserialize_with = "Option::deserialize")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: i32,
    #[serde(rename = "tombstone")]
    pub tombstone: bool,
    #[serde(rename = "version")]
    pub version: i32,
}

impl SyncEntityVersionRecord {
    pub fn new(
        content_hash: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        device_id: String,
        entity_id: String,
        entity_type: models::SyncEntityType,
        mutation_kind: models::SyncMutationKind,
        operation_id: String,
        payload: Option<std::collections::HashMap<String, serde_json::Value>>,
        schema_version: i32,
        tombstone: bool,
        version: i32,
    ) -> SyncEntityVersionRecord {
        SyncEntityVersionRecord {
            content_hash,
            created_at,
            device_id,
            entity_id,
            entity_type,
            mutation_kind,
            operation_id,
            payload,
            schema_version,
            tombstone,
            version,
        }
    }
}
