/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncError {
    #[serde(rename = "code")]
    pub code: models::SyncErrorCode,
    #[serde(
        rename = "details",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub details: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "retryable")]
    pub retryable: bool,
}

impl SyncError {
    pub fn new(code: models::SyncErrorCode, message: String, retryable: bool) -> SyncError {
        SyncError {
            code,
            details: None,
            message,
            retryable,
        }
    }
}
