/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncConflictReason {
    #[serde(rename = "concurrentCreate")]
    ConcurrentCreate,
    #[serde(rename = "divergentContent")]
    DivergentContent,
    #[serde(rename = "tombstoneDivergence")]
    TombstoneDivergence,
    #[serde(rename = "restoreDivergence")]
    RestoreDivergence,
    #[serde(rename = "renameDivergence")]
    RenameDivergence,
}

impl std::fmt::Display for SyncConflictReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ConcurrentCreate => write!(f, "concurrentCreate"),
            Self::DivergentContent => write!(f, "divergentContent"),
            Self::TombstoneDivergence => write!(f, "tombstoneDivergence"),
            Self::RestoreDivergence => write!(f, "restoreDivergence"),
            Self::RenameDivergence => write!(f, "renameDivergence"),
        }
    }
}

impl Default for SyncConflictReason {
    fn default() -> SyncConflictReason {
        Self::ConcurrentCreate
    }
}
