/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncPushResponse {
    #[serde(rename = "batchId")]
    pub batch_id: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
    #[serde(rename = "results")]
    pub results: Vec<models::SyncOperationResult>,
}

impl SyncPushResponse {
    pub fn new(
        batch_id: String,
        protocol_version: i32,
        results: Vec<models::SyncOperationResult>,
    ) -> SyncPushResponse {
        SyncPushResponse {
            batch_id,
            protocol_version,
            results,
        }
    }
}
