/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncVersionRestoreRecord {
    #[serde(rename = "acceptedContentHash")]
    pub accepted_content_hash: String,
    #[serde(rename = "acceptedVersion")]
    pub accepted_version: i32,
    #[serde(rename = "actorDeviceId")]
    pub actor_device_id: String,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    #[serde(rename = "entityType")]
    pub entity_type: models::SyncEntityType,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ProtocolVersion,
    #[serde(rename = "restoredAt")]
    pub restored_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "restoredFromVersion")]
    pub restored_from_version: i32,
    #[serde(rename = "result")]
    pub result: Box<models::SyncEntityVersionRecord>,
}

impl SyncVersionRestoreRecord {
    pub fn new(
        accepted_content_hash: String,
        accepted_version: i32,
        actor_device_id: String,
        entity_id: String,
        entity_type: models::SyncEntityType,
        operation_id: String,
        protocol_version: ProtocolVersion,
        restored_at: chrono::DateTime<chrono::FixedOffset>,
        restored_from_version: i32,
        result: models::SyncEntityVersionRecord,
    ) -> SyncVersionRestoreRecord {
        SyncVersionRestoreRecord {
            accepted_content_hash,
            accepted_version,
            actor_device_id,
            entity_id,
            entity_type,
            operation_id,
            protocol_version,
            restored_at,
            restored_from_version,
            result: Box::new(result),
        }
    }
}
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum ProtocolVersion {
    Variant1 = 1,
}

impl std::fmt::Display for ProtocolVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Variant1 => "1",
            }
        )
    }
}

impl Default for ProtocolVersion {
    fn default() -> ProtocolVersion {
        Self::Variant1
    }
}
