/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncAckRequest {
    #[serde(rename = "cursor")]
    pub cursor: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
}

impl SyncAckRequest {
    pub fn new(cursor: String, device_id: String, protocol_version: i32) -> SyncAckRequest {
        SyncAckRequest {
            cursor,
            device_id,
            protocol_version,
        }
    }
}
