/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncResolutionAction {
    #[serde(rename = "keepLocal")]
    KeepLocal,
    #[serde(rename = "useCloud")]
    UseCloud,
    #[serde(rename = "saveCopy")]
    SaveCopy,
    #[serde(rename = "manualMerge")]
    ManualMerge,
    #[serde(rename = "restoreVersion")]
    RestoreVersion,
    #[serde(rename = "undo")]
    Undo,
}

impl std::fmt::Display for SyncResolutionAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::KeepLocal => write!(f, "keepLocal"),
            Self::UseCloud => write!(f, "useCloud"),
            Self::SaveCopy => write!(f, "saveCopy"),
            Self::ManualMerge => write!(f, "manualMerge"),
            Self::RestoreVersion => write!(f, "restoreVersion"),
            Self::Undo => write!(f, "undo"),
        }
    }
}

impl Default for SyncResolutionAction {
    fn default() -> SyncResolutionAction {
        Self::KeepLocal
    }
}
