/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncPullResponse {
    #[serde(rename = "changes")]
    pub changes: Vec<models::SyncChange>,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    #[serde(rename = "nextCursor")]
    pub next_cursor: String,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: i32,
}

impl SyncPullResponse {
    pub fn new(
        changes: Vec<models::SyncChange>,
        has_more: bool,
        next_cursor: String,
        protocol_version: i32,
    ) -> SyncPullResponse {
        SyncPullResponse {
            changes,
            has_more,
            next_cursor,
            protocol_version,
        }
    }
}
