/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyncConflictSnapshot : Immutable candidate captured when personal-device sync cannot converge.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncConflictSnapshot {
    #[serde(rename = "contentHash")]
    pub content_hash: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "modifiedAt")]
    pub modified_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "mutationKind")]
    pub mutation_kind: models::SyncMutationKind,
    #[serde(rename = "payload", deserialize_with = "Option::deserialize")]
    pub payload: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: i32,
    #[serde(rename = "tombstone")]
    pub tombstone: bool,
    #[serde(rename = "version")]
    pub version: i32,
}

impl SyncConflictSnapshot {
    /// Immutable candidate captured when personal-device sync cannot converge.
    pub fn new(
        content_hash: String,
        device_id: String,
        modified_at: chrono::DateTime<chrono::FixedOffset>,
        mutation_kind: models::SyncMutationKind,
        payload: Option<std::collections::HashMap<String, serde_json::Value>>,
        schema_version: i32,
        tombstone: bool,
        version: i32,
    ) -> SyncConflictSnapshot {
        SyncConflictSnapshot {
            content_hash,
            device_id,
            modified_at,
            mutation_kind,
            payload,
            schema_version,
            tombstone,
            version,
        }
    }
}
