/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncOperationStatus {
    #[serde(rename = "applied")]
    Applied,
    #[serde(rename = "noop")]
    Noop,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "dependencyFailed")]
    DependencyFailed,
}

impl std::fmt::Display for SyncOperationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Applied => write!(f, "applied"),
            Self::Noop => write!(f, "noop"),
            Self::Conflict => write!(f, "conflict"),
            Self::Rejected => write!(f, "rejected"),
            Self::DependencyFailed => write!(f, "dependencyFailed"),
        }
    }
}

impl Default for SyncOperationStatus {
    fn default() -> SyncOperationStatus {
        Self::Applied
    }
}
