/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncMutationKind {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "restore")]
    Restore,
    #[serde(rename = "rename")]
    Rename,
    #[serde(rename = "attach")]
    Attach,
    #[serde(rename = "detach")]
    Detach,
}

impl std::fmt::Display for SyncMutationKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Create => write!(f, "create"),
            Self::Update => write!(f, "update"),
            Self::Delete => write!(f, "delete"),
            Self::Restore => write!(f, "restore"),
            Self::Rename => write!(f, "rename"),
            Self::Attach => write!(f, "attach"),
            Self::Detach => write!(f, "detach"),
        }
    }
}

impl Default for SyncMutationKind {
    fn default() -> SyncMutationKind {
        Self::Create
    }
}
