/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncConflictResolutionRequest {
    #[serde(rename = "action")]
    pub action: models::SyncResolutionAction,
    #[serde(rename = "currentContentHash")]
    pub current_content_hash: String,
    #[serde(rename = "currentVersion")]
    pub current_version: i32,
    #[serde(
        rename = "newEntityId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub new_entity_id: Option<Option<String>>,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(
        rename = "payload",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payload: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ProtocolVersion,
    #[serde(
        rename = "undoesResolutionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub undoes_resolution_id: Option<Option<String>>,
}

impl SyncConflictResolutionRequest {
    pub fn new(
        action: models::SyncResolutionAction,
        current_content_hash: String,
        current_version: i32,
        operation_id: String,
        protocol_version: ProtocolVersion,
    ) -> SyncConflictResolutionRequest {
        SyncConflictResolutionRequest {
            action,
            current_content_hash,
            current_version,
            new_entity_id: None,
            operation_id,
            payload: None,
            protocol_version,
            undoes_resolution_id: None,
        }
    }
}
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum ProtocolVersion {
    Variant1 = 1,
}

impl std::fmt::Display for ProtocolVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Variant1 => "1",
            }
        )
    }
}

impl Default for ProtocolVersion {
    fn default() -> ProtocolVersion {
        Self::Variant1
    }
}
