/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenPair {
    #[serde(rename = "accessToken")]
    pub access_token: String,
    #[serde(rename = "expiresIn")]
    pub expires_in: i32,
    #[serde(rename = "refreshExpiresIn")]
    pub refresh_expires_in: i32,
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
    #[serde(rename = "user")]
    pub user: Box<models::UserEntity>,
}

impl TokenPair {
    pub fn new(
        access_token: String,
        expires_in: i32,
        refresh_expires_in: i32,
        refresh_token: String,
        user: models::UserEntity,
    ) -> TokenPair {
        TokenPair {
            access_token,
            expires_in,
            refresh_expires_in,
            refresh_token,
            user: Box::new(user),
        }
    }
}
