/*
 * TestPaper Backend
 *
 * The canonical HTTP contract for `/api/v1`. Browser clients use Cookie + CSRF authentication; native clients inject Bearer credentials. WebSocket messages are described by `x-testpapers-websocket`.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserEntity {
    #[serde(
        rename = "avatarUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub avatar_url: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "permissions")]
    pub permissions: Vec<Permissions>,
    #[serde(rename = "publicId")]
    pub public_id: String,
    #[serde(rename = "role")]
    pub role: models::UserRole,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "username")]
    pub username: String,
}

impl UserEntity {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        display_name: String,
        id: i32,
        is_active: bool,
        permissions: Vec<Permissions>,
        public_id: String,
        role: models::UserRole,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        username: String,
    ) -> UserEntity {
        UserEntity {
            avatar_url: None,
            created_at,
            display_name,
            id,
            is_active,
            permissions,
            public_id,
            role,
            updated_at,
            username,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "questions:read")]
    QuestionsColonRead,
    #[serde(rename = "questions:write")]
    QuestionsColonWrite,
    #[serde(rename = "questions:delete")]
    QuestionsColonDelete,
    #[serde(rename = "answers:read")]
    AnswersColonRead,
    #[serde(rename = "papers:read")]
    PapersColonRead,
    #[serde(rename = "papers:write")]
    PapersColonWrite,
    #[serde(rename = "users:manage")]
    UsersColonManage,
    #[serde(rename = "banks:read")]
    BanksColonRead,
    #[serde(rename = "banks:write")]
    BanksColonWrite,
    #[serde(rename = "banks:delete")]
    BanksColonDelete,
    #[serde(rename = "banks:publish")]
    BanksColonPublish,
    #[serde(rename = "banks:subscribe")]
    BanksColonSubscribe,
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::QuestionsColonRead
    }
}
